name: Python CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Smoke test
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true
          export PYTHONPATH=./src
          python -m omniintent --help
          python -m omniintent demo --ingest samples/quest3_tiny.csv --seq-len 32
